### PR TITLE
Deprecate with offset ctx

### LINKED ISSUE #247: The examples use the deprecated `withOffsetContext` API
**Describe the bug**
Many examples in the current `master` show the use of `...WithOffsetContext()` API while these APIs have been deprecated.

**To Reproduce**
see:
./snippets/modules/ROOT/examples/akkastreams-scala/src/main/scala/cloudflow/akkastreamsdoc/RecordSumFlow.scala
./snippets/modules/ROOT/examples/akkastreams-scala/src/main/scala/com/example/MetricsEgress.scala
./taxi-ride/logger/src/main/scala/taxiride/logger/FarePerRideLogger.scala
...
and many more

**Expected behavior**
Use the current API `...withCommittableContext` API

**Additional context**
Thanks to @jasoncarreira for bringing the deprecation issue up in gitter.

### PR DESCRIPTION
**Pull request by maasg**
This PR deprecates the 'withOffsetContext' set of APIs and implements a consistent "Committable" API for sources, flows, and sinks.
It also upgrades all examples to use the new API.

Closes #247 

ping @jasoncarreira - this should address the issue that you reported. Thanks for that.

### CODE REVIEW

File: core/cloudflow-akka-testkit/src/main/scala/cloudflow/akkastream/testkit/TestContext.scala [hunk 1]
```diff
@@ -51,7 +51,13 @@ private[testkit] case class TestContext(
   override def streamletDefinition: StreamletDefinition =
     StreamletDefinition("appId", "appVersion", streamletRef, "streamletClass", List(), volumeMounts, config)
 
-  def sourceWithOffsetContext[T](inlet: CodecInlet[T]): cloudflow.akkastream.scaladsl.SourceWithOffsetContext[T] =
+  @deprecated("Use `committableSink` instead.", "1.3.4")
```
Comment (RayRoestenburg) [inline core/cloudflow-akka-testkit/src/main/scala/cloudflow/akkastream/testkit/TestContext.scala:54]: incorrect reference, probably sourceWithCommittableContext

File: core/cloudflow-akka/src/main/scala/cloudflow/akkastream/AkkaStreamletContextImpl.scala [hunk 2]
```diff
@@ -67,7 +67,8 @@ final class AkkaStreamletContextImpl(
 
   private val bootstrapServers = system.settings.config.getString("cloudflow.kafka.bootstrap-servers")
 
-  def sourceWithOffsetContext[T](inlet: CodecInlet[T]): cloudflow.akkastream.scaladsl.SourceWithOffsetContext[T] = {
+  // internal implementation that uses the CommittableOffset implementation to provide access to the underlying offsets
+  private[akkastream] def _sourceWithContext[T](inlet: CodecInlet[T]): SourceWithContext[T, CommittableOffset, _] = {
```
Comment (RayRoestenburg) [inline core/cloudflow-akka/src/main/scala/cloudflow/akkastream/AkkaStreamletContextImpl.scala:71]: no need for '_' ?

File: examples/snippets/modules/ROOT/examples/build-akka-streamlets-java/project/cloudflow-plugins.sbt [hunk 3]
```diff
@@ -1 +1 @@
-addSbtPlugin("com.lightbend.cloudflow" % "sbt-cloudflow" % "1.3.3")
+addSbtPlugin("com.lightbend.cloudflow" % "sbt-cloudflow" % "1.3.4-SNAPSHOT")
```
Comment (RayRoestenburg) [inline examples/snippets/modules/ROOT/examples/build-akka-streamlets-java/project/cloudflow-plugins.sbt:1]: Will this work in CI build? Or should you do an internalRelease and depend on that?

Comment (maasg) [reply examples/snippets/modules/ROOT/examples/build-akka-streamlets-java/project/cloudflow-plugins.sbt:1]: CI replaces the version with the cached build. I didn't want to leave this on 1.3.3 b/c it would not work. 
Part of the ongoing dilemma with `master` vs `version` in the docs.  (this is part of the docs snippets)

File: core/cloudflow-akka/src/main/scala/cloudflow/akkastream/AkkaStreamletContextImpl.scala (hunk 2 above)
Comment (maasg) [reply core/cloudflow-akka/src/main/scala/cloudflow/akkastream/AkkaStreamletContextImpl.scala:71]: I like to signal that this is for internal use only.

Comment (RayRoestenburg) [reply core/cloudflow-akka/src/main/scala/cloudflow/akkastream/AkkaStreamletContextImpl.scala:71]: the `private` gives it away right ;-)

Comment (RayRoestenburg) [reply core/cloudflow-akka/src/main/scala/cloudflow/akkastream/AkkaStreamletContextImpl.scala:71]: We don't use this naming convention so far so rather not do it.

Comment (RayRoestenburg) [reply core/cloudflow-akka/src/main/scala/cloudflow/akkastream/AkkaStreamletContextImpl.scala:71]: I see we started to use it in a few places. I'm not too happy with the style but if you _really_ like it a lot it is fine.

Comment (maasg) [reply core/cloudflow-akka/src/main/scala/cloudflow/akkastream/AkkaStreamletContextImpl.scala]: I prefer the "_" for internal impl for internal implementations of like-named public methods. But I can also go without it. The thinking behind is that you could have:
```
 def f(...) ... // public
 def _f // private implementation of f
```
you will also see me using it for recursive implementations, like:
``` 
def doThis() {
  def _doThis {//really do this
  
 }
  _doThis(init value)
}
```

Comment (maasg) [reply core/cloudflow-akka/src/main/scala/cloudflow/akkastream/AkkaStreamletContextImpl.scala]: but I removed the `_` ...  let's move on and merge this.

Comment (RayRoestenburg) [reply core/cloudflow-akka/src/main/scala/cloudflow/akkastream/AkkaStreamletContextImpl.scala]: yeah I should have not said anything TBH @maasg I need to get rid of these unimportant preferences...

Comment (RayRoestenburg) [reply core/cloudflow-akka/src/main/scala/cloudflow/akkastream/AkkaStreamletContextImpl.scala]: So in the future feel free to do this.
